import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import { toast } from "sonner";
import { middleware } from "../middleware";
import type { paths } from "./v1"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.VITE_BASE_URL,
});
fetchClient.use(middleware);

export const $api = createClient(fetchClient);

export const handleError = (error: never) => {
  try {
    const { message } = error;
    if (message) {
      toast.error("Terjadi kesalahan!", {
        description: message,
        position: "top-right",
      });
    }
  } catch (e) {
    toast.error("Terjadi kesalahan tak terduga!", {
      description: "Silahkan coba lagi nanti",
      position: "top-right",
    });
  }
};
