import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import { middleware } from "../middleware";
import type { paths } from "./v1"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.VITE_API_BASE_URL,
});
fetchClient.use(middleware);

export const $api = createClient(fetchClient);
