/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.GetAllUsers"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh-token-ttl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshTokenTTL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/students/accounts/{student_token_id}/eject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description student token id */
                    student_token_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.EjectStudentToken"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/students/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/students/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshTokenStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllBatches"];
        put?: never;
        post: operations["createBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description batch id */
                    batch_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.GetBatch"];
                    };
                };
            };
        };
        put: operations["updateBatch"];
        post?: never;
        delete: operations["deleteBatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/majors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllMajorsByBatchId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description batch id */
                    batch_id: number;
                    /** @description major id */
                    major_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.GetAllClassroomsByMajorId"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description batch id */
                    batch_id: number;
                    /** @description major id */
                    major_id: number;
                };
                cookie?: never;
            };
            /** @description body */
            requestBody: {
                content: {
                    "*/*": components["schemas"]["requests.CreateClassroom"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.CreateClassroom"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description batch id */
                    batch_id: number;
                    /** @description major id */
                    major_id: number;
                    /** @description classroom id */
                    classroom_id: number;
                };
                cookie?: never;
            };
            /** @description body */
            requestBody: {
                content: {
                    "*/*": components["schemas"]["requests.UpdateClassroom"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.UpdateClassroom"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/student-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description batch id */
                    batch_id: number;
                    /** @description major id */
                    major_id: number;
                    /** @description classroom id */
                    classroom_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.GetAllStudentAccountsByClassroomId"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllStudentsByClassroomId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description batch id */
                    batch_id: number;
                    /** @description major id */
                    major_id: number;
                    /** @description classroom id */
                    classroom_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.GetAllSubjectAttendances"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description batch id */
                    batch_id: number;
                    /** @description major id */
                    major_id: number;
                    /** @description classroom id */
                    classroom_id: number;
                };
                cookie?: never;
            };
            /** @description body */
            requestBody: {
                content: {
                    "*/*": components["schemas"]["requests.CreateSubjectAttendance"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.CreateSubjectAttendance"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/records/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description batch id */
                    batch_id: number;
                    /** @description major id */
                    major_id: number;
                    /** @description classroom id */
                    classroom_id: number;
                };
                cookie?: never;
            };
            /** @description body */
            requestBody: {
                content: {
                    "*/*": components["schemas"]["requests.CreateSubjectAttendanceRecordStudent"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.CreateSubjectAttendanceRecordStudent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/majors/{major_id}/classrooms/{classroom_id}/subject-attendances/{subject_attendance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description batch id */
                    batch_id: number;
                    /** @description major id */
                    major_id: number;
                    /** @description classroom id */
                    classroom_id: number;
                    /** @description subject attendance id */
                    subject_attendance_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.GetSubjectAttendance"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classrooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllClassrooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classrooms/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllClassroomWithMajors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/general-attendances/records/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description body */
            requestBody: {
                content: {
                    "*/*": components["schemas"]["requests.CreateGeneralAttendanceRecordStudent"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.CreateGeneralAttendanceRecordStudent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/general_attendances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllGeneralAttendances"];
        put?: never;
        post: operations["createGeneralAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/general_attendances/{general_attendance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGeneralAttendance"];
        put: operations["updateGeneralAttendance"];
        post?: never;
        delete: operations["deleteGeneralAttendance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/majors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllMajors"];
        put?: never;
        post: operations["createMajor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/majors/{major_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateMajor"];
        post?: never;
        delete: operations["deleteMajor"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllSubjects"];
        put?: never;
        post: operations["createSubject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateSubject"];
        post?: never;
        delete: operations["deleteSubject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teachers/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description file
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["responses.ImportTeacher"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GetAllStudentsByClassroomIdRes: {
            students: components["schemas"]["domains.Student"][];
        };
        GetAllStudentsRes: {
            students: components["schemas"]["domains.StudentMajorClassroom"][];
        };
        LoginReq: {
            /** @default email@email.com */
            email: string;
            password?: string;
        };
        LoginRes: {
            access_token: string;
            refresh_token: string;
        };
        LoginStudentReq: {
            device_id: string;
            nis: string;
            school_code: string;
        };
        LoginStudentRes: {
            access_token: string;
            refresh_token: string;
        };
        LogoutReq: {
            refresh_token: string;
        };
        RefreshTokenReq: {
            refresh_token?: string;
        };
        RefreshTokenRes: {
            access_token: string;
            refresh_token: string;
        };
        RefreshTokenStudentReq: {
            refresh_token: string;
        };
        RefreshTokenStudentRes: {
            access_token: string;
            refresh_token: string;
        };
        RefreshTokenTTLReq: {
            refresh_token?: string;
        };
        "api_internal_features_batch_dto_requests.Create": {
            name?: string;
        };
        "api_internal_features_batch_dto_requests.Update": {
            name?: string;
        };
        "api_internal_features_major_dto_requests.Create": {
            batch_id: number;
            name: string;
        };
        "api_internal_features_major_dto_requests.Update": {
            batch_id: number;
            name: string;
        };
        "domains.Batch": {
            id: number;
            name: string;
            school_id: number;
        };
        "domains.Classroom": {
            id: number;
            major_id: number;
            name: string;
        };
        "domains.GeneralAttendance": {
            code: string;
            datetime: string;
            id: number;
            note: string;
            school_id: number;
        };
        "domains.Major": {
            batch_id: number;
            id: number;
            name: string;
        };
        "domains.Student": {
            classroom_id: number;
            id: number;
            name: string;
            nis: string;
            school_id: number;
        };
        "domains.StudentMajorClassroom": {
            classroom: components["schemas"]["domains.Classroom"];
            major: components["schemas"]["domains.Major"];
            student: components["schemas"]["domains.Student"];
        };
        "domains.StudentToken": {
            device_id: string;
            id: number;
            refresh_token: string;
            student_id: number;
            ttl: string;
        };
        "domains.Subject": {
            id: number;
            name: string;
            school_id: number;
        };
        "domains.SubjectAttendance": {
            classroom_id: number;
            code: string;
            date_time: string;
            id: number;
            note: string;
            subject_id: number;
        };
        "domains.SubjectAttendanceSubject": {
            subject: components["schemas"]["domains.Subject"];
            subject_attendance: components["schemas"]["domains.SubjectAttendance"];
        };
        "domains.User": {
            email: string;
            id: number;
            name: string;
            password: string;
            role: string;
            school_id: number;
        };
        "dto.BatchInfo": {
            batch: components["schemas"]["domains.Batch"];
            classrooms_count: number;
            majors_count: number;
        };
        "dto.StudentAccount": {
            student: components["schemas"]["domains.Student"];
            student_token: components["schemas"]["domains.StudentToken"];
        };
        "requests.CreateClassroom": {
            name: string;
        };
        "requests.CreateGeneralAttendance": {
            datetime?: string;
            note?: string;
        };
        "requests.CreateGeneralAttendanceRecordStudent": {
            code: string;
        };
        "requests.CreateSubject": {
            name: string;
        };
        "requests.CreateSubjectAttendance": {
            datetime: string;
            note: string;
            subject_id: number;
        };
        "requests.CreateSubjectAttendanceRecordStudent": {
            code: string;
        };
        "requests.UpdateClassroom": {
            name: string;
        };
        "requests.UpdateGeneralAttendance": {
            datetime?: string;
            note?: string;
        };
        "requests.UpdateSubject": {
            name: string;
        };
        "responses.ClassroomMajor": {
            classroom: components["schemas"]["domains.Classroom"];
            major: components["schemas"]["domains.Major"];
        };
        "responses.CreateClassroom": {
            classroom: components["schemas"]["domains.Classroom"];
        };
        "responses.CreateGeneralAttendance": {
            general_attendance: components["schemas"]["domains.GeneralAttendance"];
        };
        "responses.CreateGeneralAttendanceRecordStudent": {
            message: string;
        };
        "responses.CreateSubject": {
            subject: components["schemas"]["domains.Subject"];
        };
        "responses.CreateSubjectAttendance": {
            subject_attendance: components["schemas"]["domains.SubjectAttendance"];
        };
        "responses.CreateSubjectAttendanceRecordStudent": {
            message: string;
        };
        "responses.DeleteGeneralAttendance": {
            message?: string;
        };
        "responses.DeleteSubject": {
            message: string;
        };
        "responses.EjectStudentToken": {
            message: string;
        };
        "responses.GetAll": {
            classrooms: components["schemas"]["domains.Classroom"][];
        };
        "responses.GetAllBatches": {
            batches: components["schemas"]["dto.BatchInfo"][];
        };
        "responses.GetAllClassroomWithMajors": {
            data: components["schemas"]["responses.ClassroomMajor"][];
        };
        "responses.GetAllClassroomsByMajorId": {
            classrooms: components["schemas"]["domains.Classroom"][];
        };
        "responses.GetAllGeneralAttendances": {
            general_attendances: components["schemas"]["domains.GeneralAttendance"][];
        };
        "responses.GetAllMajorsByBatchId": {
            majors: components["schemas"]["domains.Major"][];
        };
        "responses.GetAllStudentAccountsByClassroomId": {
            items: components["schemas"]["dto.StudentAccount"][];
        };
        "responses.GetAllSubjectAttendances": {
            items: components["schemas"]["domains.SubjectAttendanceSubject"][];
        };
        "responses.GetAllSubjects": {
            subjects: components["schemas"]["domains.Subject"][];
        };
        "responses.GetAllUsers": {
            users: components["schemas"]["domains.User"][];
        };
        "responses.GetBatch": {
            batch: components["schemas"]["domains.Batch"];
        };
        "responses.GetGeneralAttendance": {
            general_attendance: components["schemas"]["domains.GeneralAttendance"];
        };
        "responses.GetSubjectAttendance": {
            subject_attendance: components["schemas"]["domains.SubjectAttendance"];
        };
        "responses.ImportTeacher": {
            message: string;
        };
        "responses.Logout": Record<string, never>;
        "responses.UpdateClassroom": {
            classroom: components["schemas"]["domains.Classroom"];
        };
        "responses.UpdateGeneralAttendance": {
            general_attendance: components["schemas"]["domains.GeneralAttendance"];
        };
        "responses.UpdateSubject": {
            subject: components["schemas"]["domains.Subject"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["LoginReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginRes"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Logout Request */
        requestBody: {
            content: {
                "*/*": components["schemas"]["LogoutReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.Logout"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Refresh token req */
        requestBody: {
            content: {
                "*/*": components["schemas"]["RefreshTokenReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshTokenRes"];
                };
            };
        };
    };
    refreshTokenTTL: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Refresh token req */
        requestBody: {
            content: {
                "*/*": components["schemas"]["RefreshTokenTTLReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    loginStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["LoginStudentReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginStudentRes"];
                };
            };
        };
    };
    refreshTokenStudent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["RefreshTokenStudentReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshTokenStudentRes"];
                };
            };
        };
    };
    getAllBatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.GetAllBatches"];
                };
            };
        };
    };
    createBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["api_internal_features_batch_dto_requests.Create"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["domains.Batch"];
                };
            };
        };
    };
    updateBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description batch id */
                batch_id: number;
            };
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["api_internal_features_batch_dto_requests.Update"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["domains.Batch"];
                };
            };
        };
    };
    deleteBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description batch id */
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getAllMajorsByBatchId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description batch id */
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.GetAllMajorsByBatchId"];
                };
            };
        };
    };
    getAllStudentsByClassroomId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description batch id */
                batch_id: number;
                /** @description major id */
                major_id: number;
                /** @description classroom id */
                classroom_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetAllStudentsByClassroomIdRes"];
                };
            };
        };
    };
    getAllClassrooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.GetAll"];
                };
            };
        };
    };
    getAllClassroomWithMajors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Batch Id */
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.GetAllClassroomWithMajors"];
                };
            };
        };
    };
    getAllGeneralAttendances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.GetAllGeneralAttendances"];
                };
            };
        };
    };
    createGeneralAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["requests.CreateGeneralAttendance"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.CreateGeneralAttendance"];
                };
            };
        };
    };
    getGeneralAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description general attendance id */
                general_attendance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.GetGeneralAttendance"];
                };
            };
        };
    };
    updateGeneralAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description general attendance id */
                general_attendance_id: number;
            };
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["requests.UpdateGeneralAttendance"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.UpdateGeneralAttendance"];
                };
            };
        };
    };
    deleteGeneralAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description general attendance id */
                general_attendance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.DeleteGeneralAttendance"];
                };
            };
        };
    };
    getAllMajors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["domains.Major"][];
                };
            };
        };
    };
    createMajor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["api_internal_features_major_dto_requests.Create"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["domains.Major"];
                };
            };
        };
    };
    updateMajor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description major id */
                major_id: number;
            };
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["api_internal_features_major_dto_requests.Update"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["domains.Major"];
                };
            };
        };
    };
    deleteMajor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description major id */
                major_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getAllStudents: {
        parameters: {
            query: {
                /** @description Keyword */
                keyword: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GetAllStudentsRes"];
                };
            };
        };
    };
    getAllSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.GetAllSubjects"];
                };
            };
        };
    };
    createSubject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["requests.CreateSubject"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.CreateSubject"];
                };
            };
        };
    };
    updateSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description subject id */
                subject_id: number;
            };
            cookie?: never;
        };
        /** @description body */
        requestBody: {
            content: {
                "*/*": components["schemas"]["requests.UpdateSubject"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.UpdateSubject"];
                };
            };
        };
    };
    deleteSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description subject id */
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["responses.DeleteSubject"];
                };
            };
        };
    };
}
