/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTeacherManagementIndexRouteImport } from './routes/_authenticated/teacher-management/index'
import { Route as AuthenticatedSubjectManagementIndexRouteImport } from './routes/_authenticated/subject-management/index'
import { Route as AuthenticatedSettingIndexRouteImport } from './routes/_authenticated/setting/index'
import { Route as AuthAuthRegisterRouteImport } from './routes/_auth/auth.register'
import { Route as AuthAuthLoginRouteImport } from './routes/_auth/auth.login'
import { Route as AuthenticatedDataManagementBatchesIndexRouteImport } from './routes/_authenticated/data-management/batches/index'
import { Route as AuthenticatedAttendanceGeneralIndexRouteImport } from './routes/_authenticated/attendance/general/index'
import { Route as AuthenticatedAttendanceSubjectBatchesIndexRouteImport } from './routes/_authenticated/attendance/subject.batches/index'
import { Route as AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRouteImport } from './routes/_authenticated/attendance/general/$generalAttendanceId/index'
import { Route as AuthenticatedDataManagementBatchesBatchIdMajorsIndexRouteImport } from './routes/_authenticated/data-management/batches/$batchId.majors/index'
import { Route as AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRouteImport } from './routes/_authenticated/attendance/subject.batches/$batchId.majors/index'
import { Route as AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRouteImport } from './routes/_authenticated/data-management/batches/$batchId.majors/$majorId.classrooms/index'
import { Route as AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRouteImport } from './routes/_authenticated/attendance/subject.batches/$batchId.majors/$majorId.classrooms/index'
import { Route as AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRouteImport } from './routes/_authenticated/data-management/batches/$batchId.majors/$majorId.classrooms/$classroomId.students/index'
import { Route as AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRouteImport } from './routes/_authenticated/attendance/subject.batches/$batchId.majors/$majorId.classrooms/$classroomId.attendances/index'
import { Route as AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRouteImport } from './routes/_authenticated/attendance/subject.batches/$batchId.majors/$majorId.classrooms/$classroomId.attendances/$subjectAttendanceId/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherManagementIndexRoute =
  AuthenticatedTeacherManagementIndexRouteImport.update({
    id: '/teacher-management/',
    path: '/teacher-management/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubjectManagementIndexRoute =
  AuthenticatedSubjectManagementIndexRouteImport.update({
    id: '/subject-management/',
    path: '/subject-management/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingIndexRoute =
  AuthenticatedSettingIndexRouteImport.update({
    id: '/setting/',
    path: '/setting/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthAuthRegisterRoute = AuthAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDataManagementBatchesIndexRoute =
  AuthenticatedDataManagementBatchesIndexRouteImport.update({
    id: '/data-management/batches/',
    path: '/data-management/batches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceGeneralIndexRoute =
  AuthenticatedAttendanceGeneralIndexRouteImport.update({
    id: '/attendance/general/',
    path: '/attendance/general/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceSubjectBatchesIndexRoute =
  AuthenticatedAttendanceSubjectBatchesIndexRouteImport.update({
    id: '/attendance/subject/batches/',
    path: '/attendance/subject/batches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRoute =
  AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRouteImport.update({
    id: '/attendance/general/$generalAttendanceId/',
    path: '/attendance/general/$generalAttendanceId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataManagementBatchesBatchIdMajorsIndexRoute =
  AuthenticatedDataManagementBatchesBatchIdMajorsIndexRouteImport.update({
    id: '/data-management/batches/$batchId/majors/',
    path: '/data-management/batches/$batchId/majors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRoute =
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRouteImport.update({
    id: '/attendance/subject/batches/$batchId/majors/',
    path: '/attendance/subject/batches/$batchId/majors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRoute =
  AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRouteImport.update(
    {
      id: '/data-management/batches/$batchId/majors/$majorId/classrooms/',
      path: '/data-management/batches/$batchId/majors/$majorId/classrooms/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRoute =
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRouteImport.update(
    {
      id: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/',
      path: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRoute =
  AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRouteImport.update(
    {
      id: '/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students/',
      path: '/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRoute =
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRouteImport.update(
    {
      id: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/',
      path: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRoute =
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRouteImport.update(
    {
      id: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId/',
      path: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/setting': typeof AuthenticatedSettingIndexRoute
  '/subject-management': typeof AuthenticatedSubjectManagementIndexRoute
  '/teacher-management': typeof AuthenticatedTeacherManagementIndexRoute
  '/attendance/general': typeof AuthenticatedAttendanceGeneralIndexRoute
  '/data-management/batches': typeof AuthenticatedDataManagementBatchesIndexRoute
  '/attendance/general/$generalAttendanceId': typeof AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRoute
  '/attendance/subject/batches': typeof AuthenticatedAttendanceSubjectBatchesIndexRoute
  '/data-management/batches/$batchId/majors': typeof AuthenticatedDataManagementBatchesBatchIdMajorsIndexRoute
  '/attendance/subject/batches/$batchId/majors': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRoute
  '/data-management/batches/$batchId/majors/$majorId/classrooms': typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRoute
  '/attendance/subject/batches/$batchId/majors/$majorId/classrooms': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRoute
  '/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students': typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRoute
  '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRoute
  '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/setting': typeof AuthenticatedSettingIndexRoute
  '/subject-management': typeof AuthenticatedSubjectManagementIndexRoute
  '/teacher-management': typeof AuthenticatedTeacherManagementIndexRoute
  '/attendance/general': typeof AuthenticatedAttendanceGeneralIndexRoute
  '/data-management/batches': typeof AuthenticatedDataManagementBatchesIndexRoute
  '/attendance/general/$generalAttendanceId': typeof AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRoute
  '/attendance/subject/batches': typeof AuthenticatedAttendanceSubjectBatchesIndexRoute
  '/data-management/batches/$batchId/majors': typeof AuthenticatedDataManagementBatchesBatchIdMajorsIndexRoute
  '/attendance/subject/batches/$batchId/majors': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRoute
  '/data-management/batches/$batchId/majors/$majorId/classrooms': typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRoute
  '/attendance/subject/batches/$batchId/majors/$majorId/classrooms': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRoute
  '/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students': typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRoute
  '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRoute
  '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_auth/auth/login': typeof AuthAuthLoginRoute
  '/_auth/auth/register': typeof AuthAuthRegisterRoute
  '/_authenticated/setting/': typeof AuthenticatedSettingIndexRoute
  '/_authenticated/subject-management/': typeof AuthenticatedSubjectManagementIndexRoute
  '/_authenticated/teacher-management/': typeof AuthenticatedTeacherManagementIndexRoute
  '/_authenticated/attendance/general/': typeof AuthenticatedAttendanceGeneralIndexRoute
  '/_authenticated/data-management/batches/': typeof AuthenticatedDataManagementBatchesIndexRoute
  '/_authenticated/attendance/general/$generalAttendanceId/': typeof AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRoute
  '/_authenticated/attendance/subject/batches/': typeof AuthenticatedAttendanceSubjectBatchesIndexRoute
  '/_authenticated/data-management/batches/$batchId/majors/': typeof AuthenticatedDataManagementBatchesBatchIdMajorsIndexRoute
  '/_authenticated/attendance/subject/batches/$batchId/majors/': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRoute
  '/_authenticated/data-management/batches/$batchId/majors/$majorId/classrooms/': typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRoute
  '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRoute
  '/_authenticated/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students/': typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRoute
  '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRoute
  '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId/': typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/setting'
    | '/subject-management'
    | '/teacher-management'
    | '/attendance/general'
    | '/data-management/batches'
    | '/attendance/general/$generalAttendanceId'
    | '/attendance/subject/batches'
    | '/data-management/batches/$batchId/majors'
    | '/attendance/subject/batches/$batchId/majors'
    | '/data-management/batches/$batchId/majors/$majorId/classrooms'
    | '/attendance/subject/batches/$batchId/majors/$majorId/classrooms'
    | '/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students'
    | '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances'
    | '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/setting'
    | '/subject-management'
    | '/teacher-management'
    | '/attendance/general'
    | '/data-management/batches'
    | '/attendance/general/$generalAttendanceId'
    | '/attendance/subject/batches'
    | '/data-management/batches/$batchId/majors'
    | '/attendance/subject/batches/$batchId/majors'
    | '/data-management/batches/$batchId/majors/$majorId/classrooms'
    | '/attendance/subject/batches/$batchId/majors/$majorId/classrooms'
    | '/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students'
    | '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances'
    | '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_auth/auth/login'
    | '/_auth/auth/register'
    | '/_authenticated/setting/'
    | '/_authenticated/subject-management/'
    | '/_authenticated/teacher-management/'
    | '/_authenticated/attendance/general/'
    | '/_authenticated/data-management/batches/'
    | '/_authenticated/attendance/general/$generalAttendanceId/'
    | '/_authenticated/attendance/subject/batches/'
    | '/_authenticated/data-management/batches/$batchId/majors/'
    | '/_authenticated/attendance/subject/batches/$batchId/majors/'
    | '/_authenticated/data-management/batches/$batchId/majors/$majorId/classrooms/'
    | '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/'
    | '/_authenticated/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students/'
    | '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/'
    | '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher-management/': {
      id: '/_authenticated/teacher-management/'
      path: '/teacher-management'
      fullPath: '/teacher-management'
      preLoaderRoute: typeof AuthenticatedTeacherManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subject-management/': {
      id: '/_authenticated/subject-management/'
      path: '/subject-management'
      fullPath: '/subject-management'
      preLoaderRoute: typeof AuthenticatedSubjectManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setting/': {
      id: '/_authenticated/setting/'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AuthenticatedSettingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/auth/register': {
      id: '/_auth/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/login': {
      id: '/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/data-management/batches/': {
      id: '/_authenticated/data-management/batches/'
      path: '/data-management/batches'
      fullPath: '/data-management/batches'
      preLoaderRoute: typeof AuthenticatedDataManagementBatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/general/': {
      id: '/_authenticated/attendance/general/'
      path: '/attendance/general'
      fullPath: '/attendance/general'
      preLoaderRoute: typeof AuthenticatedAttendanceGeneralIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/subject/batches/': {
      id: '/_authenticated/attendance/subject/batches/'
      path: '/attendance/subject/batches'
      fullPath: '/attendance/subject/batches'
      preLoaderRoute: typeof AuthenticatedAttendanceSubjectBatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/general/$generalAttendanceId/': {
      id: '/_authenticated/attendance/general/$generalAttendanceId/'
      path: '/attendance/general/$generalAttendanceId'
      fullPath: '/attendance/general/$generalAttendanceId'
      preLoaderRoute: typeof AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-management/batches/$batchId/majors/': {
      id: '/_authenticated/data-management/batches/$batchId/majors/'
      path: '/data-management/batches/$batchId/majors'
      fullPath: '/data-management/batches/$batchId/majors'
      preLoaderRoute: typeof AuthenticatedDataManagementBatchesBatchIdMajorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/subject/batches/$batchId/majors/': {
      id: '/_authenticated/attendance/subject/batches/$batchId/majors/'
      path: '/attendance/subject/batches/$batchId/majors'
      fullPath: '/attendance/subject/batches/$batchId/majors'
      preLoaderRoute: typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-management/batches/$batchId/majors/$majorId/classrooms/': {
      id: '/_authenticated/data-management/batches/$batchId/majors/$majorId/classrooms/'
      path: '/data-management/batches/$batchId/majors/$majorId/classrooms'
      fullPath: '/data-management/batches/$batchId/majors/$majorId/classrooms'
      preLoaderRoute: typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/': {
      id: '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/'
      path: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms'
      fullPath: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms'
      preLoaderRoute: typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students/': {
      id: '/_authenticated/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students/'
      path: '/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students'
      fullPath: '/data-management/batches/$batchId/majors/$majorId/classrooms/$classroomId/students'
      preLoaderRoute: typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/': {
      id: '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/'
      path: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances'
      fullPath: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances'
      preLoaderRoute: typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId/': {
      id: '/_authenticated/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId/'
      path: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId'
      fullPath: '/attendance/subject/batches/$batchId/majors/$majorId/classrooms/$classroomId/attendances/$subjectAttendanceId'
      preLoaderRoute: typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingIndexRoute: typeof AuthenticatedSettingIndexRoute
  AuthenticatedSubjectManagementIndexRoute: typeof AuthenticatedSubjectManagementIndexRoute
  AuthenticatedTeacherManagementIndexRoute: typeof AuthenticatedTeacherManagementIndexRoute
  AuthenticatedAttendanceGeneralIndexRoute: typeof AuthenticatedAttendanceGeneralIndexRoute
  AuthenticatedDataManagementBatchesIndexRoute: typeof AuthenticatedDataManagementBatchesIndexRoute
  AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRoute: typeof AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRoute
  AuthenticatedAttendanceSubjectBatchesIndexRoute: typeof AuthenticatedAttendanceSubjectBatchesIndexRoute
  AuthenticatedDataManagementBatchesBatchIdMajorsIndexRoute: typeof AuthenticatedDataManagementBatchesBatchIdMajorsIndexRoute
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRoute: typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRoute
  AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRoute: typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRoute
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRoute: typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRoute
  AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRoute: typeof AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRoute
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRoute: typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRoute
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRoute: typeof AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingIndexRoute: AuthenticatedSettingIndexRoute,
  AuthenticatedSubjectManagementIndexRoute:
    AuthenticatedSubjectManagementIndexRoute,
  AuthenticatedTeacherManagementIndexRoute:
    AuthenticatedTeacherManagementIndexRoute,
  AuthenticatedAttendanceGeneralIndexRoute:
    AuthenticatedAttendanceGeneralIndexRoute,
  AuthenticatedDataManagementBatchesIndexRoute:
    AuthenticatedDataManagementBatchesIndexRoute,
  AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRoute:
    AuthenticatedAttendanceGeneralGeneralAttendanceIdIndexRoute,
  AuthenticatedAttendanceSubjectBatchesIndexRoute:
    AuthenticatedAttendanceSubjectBatchesIndexRoute,
  AuthenticatedDataManagementBatchesBatchIdMajorsIndexRoute:
    AuthenticatedDataManagementBatchesBatchIdMajorsIndexRoute,
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRoute:
    AuthenticatedAttendanceSubjectBatchesBatchIdMajorsIndexRoute,
  AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRoute:
    AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsIndexRoute,
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRoute:
    AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsIndexRoute,
  AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRoute:
    AuthenticatedDataManagementBatchesBatchIdMajorsMajorIdClassroomsClassroomIdStudentsIndexRoute,
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRoute:
    AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesIndexRoute,
  AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRoute:
    AuthenticatedAttendanceSubjectBatchesBatchIdMajorsMajorIdClassroomsClassroomIdAttendancesSubjectAttendanceIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
